id = "gossamer"
name = "Gossamer"
description = "Gossamer language support for Zed."
version = "0.2.0"
schema_version = 1
authors = ["Gossamer contributors"]
repository = "https://github.com/gossamer-lang/gossamer-editor-support"

[grammars.gossamer]
repository = "https://github.com/gossamer-lang/gossamer-editor-support"
commit = "6d9c617796c903f85c3667a94e86071d1f25c8d3"
path = "tree-sitter-gossamer"

[language_servers.gossamer-lsp]
name = "gossamer-lsp"
language = "Gossamer"
