id = "gossamer"
name = "Gossamer"
description = "Gossamer language support for Zed."
version = "0.2.0"
schema_version = 1
authors = ["Gossamer contributors"]
repository = "https://github.com/gossamer-lang/gossamer-editor-support"

[grammars.gossamer]
repository = "https://github.com/gossamer-lang/gossamer-editor-support"
commit = "4ba85695b58fca5fed46baafe32968300534c1e1"
path = "tree-sitter-gossamer"

[language_servers.gossamer-lsp]
name = "gossamer-lsp"
language = "Gossamer"
